version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: todo-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - todo_postgres_data:/var/lib/postgresql/data

volumes:
  todo_postgres_data:
